baseURL: "https://alberttzhao.github.io"
languageCode: "en-us"
title: "Albert Zhao Portfolio"
theme: hugo-profile

outputs:
  home:
    - "HTML"
    - "RSS"
    - "JSON"
  page:
    - "HTML"
    - "RSS"

Paginate: 3
enableRobotsTXT: true
# disqusShortname: your-disqus-shortname
# googleAnalytics: G-MEASUREMENT_ID

markup:
  goldmark:
    renderer:
      unsafe: true

Menus:
  main:
    # - identifier: blog
    #   name: Blog
    #   title: Blog posts
    #   url: /blogs
    #   weight: 1
    - identifier: gallery
      name: Gallery
      title: Blog posts
      url: /gallery
      weight: 2
    #Dropdown menu
    # - identifier: dropdown
    #   title: Example dropdown menu
    #   name: Dropdown
    #   weight: 3
    # - identifier: dropdown1
    #   title: example dropdown 1
    #   name: example 1
    #   url: /#
    #   parent: dropdown
    #   weight: 1
    # - identifier: dropdown2
    #   title: example dropdown 2
    #   name: example 2
    #   url: /#
    #   parent: dropdown
    #   weight: 2

params:
  title: "Albert Zhao"
  description: Personal Portfolio
  # staticPath: ""  # The path to serve the static files from
  favicon: "/logo.png"

  # Whether to serve bootstrap css and js files from CDN or not. Can be set to true, "css" or "js" to choose between
  # serving both, only the css, or only the js files through the CDN. Any other value will make so that CDN is not used.
  # Note the lack of "" in true, it should be of boolean type.
  useBootstrapCDN: false

  # If you want to load dynamically responsive images from Cloudinary
  # This requires your images to be uploaded + hosted on Cloudinary
  # Uncomment and change YOUR_CLOUD_NAME to the Cloud Name in your Cloudinary console
  # cloudinary_cloud_name: "YOUR_CLOUD_NAME"

  # Whether to add mathjax support on all pages. Alternatively, you can opt-in per page by adding `mathjax: true` in the frontmatter.
  mathjax: false

  # Whether the fade animations on the home page will be enabled
  animate: true

  theme:
    disableThemeToggle: true
    defaultTheme: "dark" # light

  font:
    fontSize: 1rem # default: 1rem
    fontWeight: 400 # default: 400
    lineHeight: 1.5 # default: 1.5
    textAlign: left # default: left

  # color preference
  # When using hex codes for colors, quotations must be used along with the # sign
  # color:
  #   textColor: "#343a40"
  #   secondaryTextColor: "#6c757d"
  #   textLinkColor: "#007bff"
  #   backgroundColor: "#eaedf0"
  #   secondaryBackgroundColor: "#64ffda1a"
  #   primaryColor: "#007bff"
  #   secondaryColor: "#f8f9fa"

  #   darkmode:
  #     textColor: "#e4e6eb"
  #     secondaryTextColor: "#b0b3b8"
  #     textLinkColor: "#ffffff"
  #     backgroundColor: "#18191a"
  #     secondaryBackgroundColor: "#212529"
  #     primaryColor: "#ffffff"
  #     secondaryColor: "#212529"

  # If you want to customize the menu, you can change it here
  navbar:
    align: ms-auto # Left: ms-auto | center: mx-auto | right: me-auto | Default: ms-auto
    # brandLogo: "/logo.png" # Logo for the brand | default is the favicon variable
    # showBrandLogo: false # Show brand logo in nav bar | default is true
    brandName: "Albert Zhao" # Brand name for the brand | default is the title variable
    disableSearch: true
    # searchPlaceholder: "Search"
    stickyNavBar:
      enable : true
      showOnScrollUp : true
    enableSeparator: false
    menus:
      disableAbout: false
      disableExperience: false
      disableEducation: false
      disableProjects: false
      disableAchievements: false
      disableContact: false

  # Hero
  hero:
    enable: true
    intro: ""
    title: "Albert Zhao"
    subtitle: "Computer Engineering and Business Adminstration"
    content: "Please see below to learn more about me, my skills, experiences, and my life. Feel free to reach out to me. "
    image: /images/paris.jpeg
    bottomImage:
      enable: true
    # roundImage: true # Make hero image circular | default false
    button:
      enable: true
      name: "Resume"
      url: "/albert-resume.pdf"
      download: false
      newPage: true
    socialLinks:
      fontAwesomeIcons:
        - icon: fab fa-github
          url: https://github.com/alberttzhao
        # - icon: fab fa-linkedin
        # url: https://example.com
      customIcons:
        - icon: /images/linkedin-icon.png
          url: https://www.linkedin.com/in/albertzhaoo/
        - icon: /images/email-icon.png
          url: mailto:gurusabarisha@gmail.com

  # About
  about:
    enable: true
    title: "About Me"
    image: "/images/headshot.jpg"
    content: |-
      My name is **<u>Albert Zhao</u>**, and I am currently a 4th year undergraduate student at Boston University (Class of 2025), pursuing a major in <u>Computer Engineering</u> and a minor in <u>Business Administration</u>.

      I have always had a passion for using my skills and knowledge to contribute to something meaningful—something that will have a positive impact on my team, the company, or people around the world. I have been fortunate to work with amazing people, teams, and companies throughout my college career, which has allowed me to further develop my technical skills and interests while contributing to real projects.

      As my most recent internship concludes, I am seeking new opportunities to learn, grow, and contribute. I am open to opportunities in the fields of computer engineering and software engineering. See below for a quick overview of my skills and expertise.
    skills:
      enable: true
      title: "Skills and Expertise: "
      items:
        - "Data Structures & Algorithms"
        - "Object Oriented Programming"
        - "C++, C, Python"
        - Git, APIs, SQL
        - SystemVerilog, UVM, FPGA, Logic Design

  # Experience
  experience:
    enable: true
    # title: "Custom Name"
    items:
      - job: "Design Verification Intern"
        company: "Marvell Technology"
        companyUrl: "https://www.marvell.com/"
        date: "May 2024 - August 2024"
        info:
          enable: false
        featuredLink:
          enable: false
          name: "View the project"
          url: "https://example.com"
        content: | 
          I worked as a Design Verification Intern at Marvell Technology, Inc in the summer of 2024. I was responsible for preparing test plan and develop verification environment in UVM (Universal Verification Methodology).

          For the first few weeks of the internship, I learned the basics of SystemVerilog and UVM using internal company resources. I also learned from other team members about the general verification process including pre-silicon and post silicon processings validation.

          Then for the rest of the internship, I worked on an reactive agent in UVM. The details of the project are confidential, but I gained hands-on knowledge and experience with UVM, RTL design and verification. 

          Overall, it was a great summer internship and I learned a lot from my mentors and other members on the team. I received a full-time return offer near the end of my intership; however, I declined it to pursue other opportunities in the field of engineering.

          <u>Skills</u>:
          - SystemVerilog
          - Universal Verification Methodology (UVM)
          - Object-Oriented Programming (OOP)
          - RTL Design
          - Pre-silicon and post-silicon validation


      - job: "Cyber-Physical System Research Associate"
        company: "BU CIDAR Lab"
        companyUrl: "https://www.cidarlab.org/"
        date: "June 2023 - Sep 2023"
        featuredLink:
          enable: true
          url: "https://cidarlabsummer23albert.owlstown.net/"
        info:
          enable: false
          content: I worked as a software developer for more than one year in Amazon.
        content: |
          I worked as a Cyber-Physical System Research Associate at Boston University CIDAR Lab in the summer of 2023. I was responsible for developing a housing for an aquatic environment monitoring and testing system, as well as developing software algorithms and interfaces for the automation and subsystem integration of the DepMaM Project.

          Through my summer research, I developed a high-precision syringe pump with a 3D-printed holder and high-precision stepper motors. My syringe pump ensured precise liquid dispensing into the microfluidics device for aquatic environment testing, while reducing costs and improving portability and compatibility. I used stepper motors, a Raspberry Pi, and Python to develop the syringe pump and its algorithms. I also developed a software algorithm to control the stepper motor speeds and to interface with the microfluidics device, allowing users to easily adjust the dispensing speed through the software interface.

          In addition to my software efforts, I also used CAD to develop a housing for the aquatic environment monitoring and testing system. The housing was designed to hold multiple tubes with different water samples and qualities, as well as pumps and controls for the system.

          <u>Skills</u>:
          - Python
          - C++
          - Raspberry Pi
          - Embedded Systems
          - CAD
          - 3D Printing

      - job: "Software Developer Intern"
        company: "Elevo·ai"
        companyUrl: "https://example.com"
        date: "July 2022 - Sep 2022"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: |
          Elevo.ai is a solutions provider startup specializing in developing intelligent tools that enhance business decision-making and operational efficiency. During my time at Elevo.ai, I worked on improving the company's data infrastructure and processing capabilities.

          I implemented clickstream data processing using Java, Python, Apache Kafka, and Rudderstack, significantly enhancing how data was collected and analyzed. By consolidating diverse data sets into a unified cloud environment, I optimized operational workflows, making data management more efficient and streamlined.

          Additionally, I integrated Apache Kafka into the company's business website, which resulted in a 40% reduction in energy consumption during data transfers, directly contributing to Elevo.ai's sustainability efforts. Alongside these technical achievements, I conducted extensive market research on emerging trends, customer needs, and preferences in the AI industry, helping guide the company's strategic direction.

          <u>Skills</u>:
          - Java
          - Python
          - Apache Kafka
      
      - job: "Automation and Robotics Research Associate"
        company: "SJSU ARMS Lab"
        companyUrl: "https://sites.google.com/sjsu.edu/armslab/home"
        date: "June 2017 - Nov 2019"
        featuredLink:
          enable: false
          url: "https://example.com"
        info:
          enable: false
        content: |
          The SJSU ARMS (Assistive Robotics and Medical System) Lab focuses on developing advanced robotics systems aimed at rehabilitation, human-robot interaction, and assistive technology. As part of my work in the lab, I designed a robotic exoskeleton limb to advance rehabilitative technology for individuals with mobility impairments, ensuring safe and compliant human interaction.

          I constructed a functional exoskeleton prototype utilizing CAD, Python, and C++ to improve mobility for paralysis patients. To enhance its effectiveness, I refined motor torque using C programming, ensuring seamless and regulated operation. I also engineered adaptive motors that could dynamically synchronize power and speed adjustments in response to patient movements, contributing to more natural and supportive motion for the users.

          <u>Skills</u>:
          - Python
          - C
          - C++
          - Motor Control

  # Education
  education:
    enable: true
    # title: "Custom Name"
    index: false
    items:
      - title: "B.S. in Computer Engineering"
        school:
          name: "Boston University, College of Engineering"
          url: "https://example.org"
        date: "2021 - Current (Expected May 2025)"
        GPA: "3.6 out of 4.0"
        content: |-
          <u>Concentrations</u>: 
            - **Machine Learning Concentration** - provides skills to apply, adapt, and design machine learning algorithms
            - **Technology Innovation Concentration** - focuses on developing an entrepreneurial mindset for engineers

          <u>Relevant Coursework</u>
            - EC528 Cloud Computing
            - EC523 Deep Learning
            - EC414 Intro to Machine Learning
            - EC440 Intro to Operating Systems
            - EC441 Intro to Computer Networking
            - CS411 Software Engineering
            - EC330 Applied Algorithms
            - EC413 Computer Organization
            - EC311 Intro to Logic Design
      - title: "minor in Business Administration"
        school:
          name: "Boston University, Questrom School of Business"
          url: "https://www.bu.edu/questrom/"
        date: "2021 - 2025"
        GPA: "3.7 out of 4.0"
        content: |-
          <u>Relevant Coursework</u>
            - SI482 Strategy for Tech Based Firms
            - SI464 Intellectual Property Law and Strategy
            - SI480 Business of Tech Innovation
            - AC221 Financial Accounting
            - SM132 Measuring Financial Values
            - SM131 Business Ethnics and Values
        featuredLink:
          enable: false
          name: "My academic record"
          url: "https://example.com"
      - title: "High School"
        school:
          name: "Valley Christian High, San Jose, CA"
          url: "https://example.org"
        GPA: "4.3 out of 5.0"
        date: "2017 - 2021"
        featuredLink:
          enable: false
          url: "https://example.com"

  # Achievements
  achievements:
    enable: false
    # title: "Custom Name"
    items:
      - title: Google kickstart runner
        content: I solved all problems with optimal solution.
        url: https://example.com
        image: /images/achievment.jpg
      - title: Facebook Hackathon Winner
        content: Developed a product using Artificial Intelligence.
        image: /images/achievment.jpg
      - title: Hugo Profile
        content: Developed a theme and getting 1K+ downloads per month.
        url: "https://github.com/gurusabarish/hugo-profile"
        image: /images/achievment.jpg
      - title: Microsoft Imagine Runner
        content: We are developed a product which can help others.
      - title: Google Summer of Code
        content: Contributed to a open source project.
        url: https://example.com

  # projects
  projects:
    enable: true
    # title: "Custom Name"
    items:
      - title: Ansible Wrangler Automation
        content: A cloud-integrated solution that automates incident resolution by generating and managing Ansible playbooks through ServiceNow, LLMs, and GitHub. (Currently Working)
        image: /images/ansible-wrangler.png
        featured:
          name: Github
          link: https://github.com/EC528-Fall-2024/ansible-wrangler
        badges:
          - "Rest API"
          - "ServiceNow"
          - "Git"
          - "LLMs"
          - "Python" 
          - "Cloud"
        links:
          # - icon: fa fa-envelope
          #  url: mailto:?subject=Hugo%20Profile%20Template&body=Check%20it%20out:%20https%3a%2f%2fhugo-profile.netlify.app%2fblog%2fmarkdown-syntax%2f
          - icon: fab fa-github
            url: https://github.com/EC528-Fall-2024/ansible-wrangler
          # - icon: fab fa-twitter
          #  url: https://twitter.com/intent/tweet?text=Check+it+out:&url=https%3A%2F%2Fgithub.com%2Fgurusabarish%2Fhugo-profile

      - title: Bike Guard
        content: Smart device to detect theft attempts on biks uding vibration, motion, proximity and machine algorithms. (Currently Working)
        image: /images/bike-guard.png
        featured:
          name: Github
          link: www.example.com
        badges:
          - "Machine Learning"
          - "Algorithms"
          - "Embedded Systems"
        links:
          - icon: fab fa-github
            url: www.example.com

      - title: FoodPal
        content: Don't know what to make? Foodpal is an easy-to-use recipt suggestion algorithm and generator based on your preferences. It also automatically orders the ingredients for you on DoorDash! 
        image: /images/foodpal.png
        featured:
          name: Github
          link: https://github.com/jdsuh50/CS411-Team-Project
        badges:
          - "SQL"
          - "APIs"
          - Python
        links:
          - icon: fab fa-github
            url: https://github.com/jdsuh50/CS411-Team-Project

  #Contact
  contact:
    enable: true
    # title: "Custom Name"
    content: |
      Don't hesitate to reach out to me if you have any questions or would like to connect. I am always open to new opportunities, meet new people, and learn new knowledge and skills. 
    btnName: Email Me
    btnLink: mailto:albertz@bu.edu
    formspree:
      enable: false # `contact.email` value will be ignored
      formId: abcdefgh # Take it from your form's endpoint, like 'https://formspree.io/f/abcdefgh'
      emailCaption: "albertz@bu.edu"
      messageCaption: "Enter your message here"
      messageRows: 5

  footer:
    recentPosts:
      path: "blogs"
      count: 3
      title: Recent Posts
      enable: true
      disableFeaturedImage: false
    socialNetworks:
      github: https://alberttzhao.github.io
      linkedin: https://www.linkedin.com/in/albertzhaoo/
      # twitter: https://twitter.com
      # instagram: https://instagram.com
      # facebook: https://facebook.com

  # List pages like blogs and posts
  listPages:
    disableFeaturedImage: false

  # Single pages like blog and post
  singlePages:
    socialShare: true
    readTime:
      enable: true
      content: "min read"
    scrollprogress:
      enable: true
    tags:
      openInNewTab: true

  # For translations
  terms:
    read: "Read"
    toc: "Table Of Contents"
    copyright: "All rights reserved"
    pageNotFound: "Page not found"
    emailText: "Check out this site"

  datesFormat:
    article: "Jan 2, 2006"
    articleList: "Jan 2, 2006"
    articleRecent: "Jan 2, 2006"

  #customScripts: -| # You can add custom scripts which will be added before </body> tag
  #  <script type="text/javascript"><!-- any script here --></script>
